# Generated by Django 5.2.7 on 2025-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_created_at_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
